#!/bin/bash
lsblk
echo "Which device will be formatted?"
read device
echo $device" will be formatted"

# create partitions
parted --script $device \
mklabel gpt \
mkpart ArchBoot fat32 0% 800Mib \
mkpart ArchRoot ext4 1000Mib 6000Mib \
mkpart ArchHome ext4 6000Mib 100%

boot_partition="$device"1
root_partition="$device"2
home_partition="$device"3

mkfs.fat -F32 $boot_partition  
wait
mkfs.ext4 $root_partition  
wait
mkfs.ext4 $home_partition  
wait
lsblk
read -p "press any key"
# mount root partition
echo "MOUNTING ROOT"
mount $root_partition /mnt 
wait
# mount home partition 
mkdir /mnt/home
mkdir /mnt/home/sm
echo "MOUNTING HOME"
mount $home_partition /mnt/home
echo "MAKING SWAP"
mkdir /swapfile
fallocate -l 6000M /swapfile
wait
ls -lh /swapfile

echo "MAKING BOOT DIRECTORY"
mkdir /mnt/boot
mkdir /mnt/boot/efi  
wait

echo "MOUNTING BOOT DIRECTORY"
mount $boot_partition /mnt/boot/efi  
wait
lsblk
read -p "Do these mounts look right? press any key"

# generate fstab
echo "GENERATING /etc/fstab"
genfstab -U /mnt >> /mnt/etc/fstab 
wait

lsblk
cat /mnt/etc/fstab
read -p "Do these partitions and devices look right?"

# install packages
pacstrap /mnt base base-devel linux linux-firmware efibootmgr grub os-prober sudo nano vim
wait
chmod +x ./arch_install2
wait
cp ./arch_install2 /mnt
cp ./arch_install3 /mnt
cp ./arch_install4 /mnt
wait

echo "END SCRIPT 1"
# mount /mnt
wait
arch-chroot /mnt ./arch_install2 2>&1 | tee  ./log.txt
wait 
