#!/bin/bash

function chroot_commands() {
# set time and date
timedatectl set-ntp true  
# set time zone
ln -sf /usr/share/zoneinfo/America/Indianapolis /etc/localtime  
wait
# enable hardware clock
hwclock --systohc  
wait
# generate locale 
sed -i '/s/# en_US.UTF-8 UTF-8/en_US.UTF-8 UTF-8' /etc/locale.gen
locale-gen  
#add hostname
echo ArchVM > /etc/hostname
wait
# add hosts
echo '127.0.0.1	localhost' > /etc/hosts  
echo '::1	localhost' >> /etc/hosts  
echo '127.0.1.1 sm@ArchVM' >>  /etc/hosts  
# set root password
passwd  

# grub installation 
echo "GRUB INSTALLATION"
grub-install --target=x86_64-efi --efi-directory=/boot/efi --bootloader-id=GRUB  
wait
grub-mkconfig -o /boot/grub/grub.cfg  
lsblk
read -p "press any key"
echo "GENERATING INITRAMFS"
# generate initramfs
mkinitcpio -P  
wait
wait
# add user and set password after installation
echo "ADDING USER"
usermod -aG wheel sm  
wait
passwd sm
wait
echo "EDITING SUDOERS FILE"
wait
# edit sudoers file to allow wheel to do anything
sed -i 's/# %wheel ALL=(ALL:ALL) ALL/%wheel ALL=(ALL:ALL) ALL/' /etc/sudoers  
# create user and set password
mkdir /home
mkdir /home/sm
mkdir /home/sm/Audio
mkdir /home/sm/Pictures
mkdir /home/sm/Documents
mkdir /home/sm/bin
chown -R sm /home/sm
echo "INSTALLING PACKAGES AS SM"
sudo -H -u sm bash -c 'sudo pacman -Syu --noconfirm && sudo pacman -Sy --noconfirm amd-ucode intel-ucode inet-tools inetutils tproute2  git networkmanager dhcp ufw man-pages tldr && sudo systemctl enable NetworkManager && systemctl enable dhcpd && sudo systemctl enable ufw && sudo systemctl status NetworkManager && sudo systemctl status ufw && sudo systemctl status dhcpd'
#sudo pacman -Sy --noconfirm xorg-xinit xorg-server i3-gaps xclip pulseeffects hunar thunar-volman thunar-archive-plugin thunar-media-tags-plugin nitrogen vlc terminator firefox w3m clamav clamtk conky

echo "DONE"
exit
}

chroot_commands
exit
