#!/bin/bash
# install grub
boot_partition=$device"1"
root_partition=$device"2"
home_partition=$device"3"

echo 
grub-install --target=x86_64-efi --bootloader-id=GRUB --efi-directory=/boot/efi --recheck 2>/errors.txt
wait
grub-mkconfig -o /boot/grub/grub.cfg 2>/errors.txt
# set root password
wait

su sm 
sudo pacman -Sy --noconfirm xorg-xinit xorg-server i3-gaps xclip man-pages pulseeffects net-tools inetutils xclip man-pages tldr thunar thunar-volman thunar-archive-plugin thunar-media-tags-plugin nitrogen vlc terminator firefox w3m clamav clamtk conky

wait

# exit chroot
exit
